/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LandingScreen: typeof import('./src/components/screens/LandingScreen.vue')['default']
    LanguageToggle: typeof import('./src/components/LanguageToggle.vue')['default']
    Message: typeof import('primevue/message')['default']
    ProductScannerModal: typeof import('./src/components/ProductScannerModal.vue')['default']
    ProductSelectionScreen: typeof import('./src/components/screens/ProductSelectionScreen.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    QuantityScreen: typeof import('./src/components/screens/QuantityScreen.vue')['default']
    ReviewScreen: typeof import('./src/components/screens/ReviewScreen.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StepHeader: typeof import('./src/components/StepHeader.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
